import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Header from '@/components/Header/Header';

const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Cumpers',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/TravelTrucks.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Toaster position="top-right" />
        <TanStackProvider>
          <Header />
          <main>{children}</main>
        </TanStackProvider>
      </body>
    </html>
  );
}
