import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Header from '@/components/Header/Header';
import ScrollToTopButton from '@/components/ScrollToTopBtn/ScrollToTopBtn';

const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Toaster position="top-right" />
        <TanStackProvider>
          <Header />
          {children}
          <ScrollToTopButton showAfter={700} />
        </TanStackProvider>
      </body>
    </html>
  );
}